language: csharp
mono: none
dotnet: 2.2
script: 
  - dotnet build src/DataValidator.sln
  - dotnet test DataValidator.Tests/DataValidator.Tests.csproj
after_success:
    - bash <(curl -s https://codecov.io/bash)
